
package soapClient.ClientService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductSoap", targetNamespace = "http://SoapServices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductSoap {


    /**
     * 
     * @param product
     */
    @WebMethod
    @Action(input = "http://SoapServices/ProductSoap/createProductRequest", output = "http://SoapServices/ProductSoap/createProductResponse")
    public void createProduct(
        @WebParam(name = "Product", partName = "Product")
        ProductEntity product);

    /**
     * 
     * @param productId
     * @return
     *     returns soapservices.ProductEntity
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SoapServices/ProductSoap/getProductRequest", output = "http://SoapServices/ProductSoap/getProductResponse")
    public ProductEntity getProduct(
        @WebParam(name = "ProductId", partName = "ProductId")
        int productId);

    /**
     * 
     * @param productId
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SoapServices/ProductSoap/getProductPriceRequest", output = "http://SoapServices/ProductSoap/getProductPriceResponse")
    public double getProductPrice(
        @WebParam(name = "ProductId", partName = "ProductId")
        int productId);

    /**
     * 
     * @param productId
     */
    @WebMethod
    @Action(input = "http://SoapServices/ProductSoap/deleteProductRequest", output = "http://SoapServices/ProductSoap/deleteProductResponse")
    public void deleteProduct(
        @WebParam(name = "ProductId", partName = "ProductId")
        int productId);

    /**
     * 
     * @param productId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://SoapServices/ProductSoap/getProductNameRequest", output = "http://SoapServices/ProductSoap/getProductNameResponse")
    public String getProductName(
        @WebParam(name = "ProductId", partName = "ProductId")
        int productId);

}
