
package soapClient.ClientService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductSoapService", targetNamespace = "http://SoapServices/", wsdlLocation = "http://localhost:8080/a20da21/ProductSoapService?wsdl")
public class ProductSoapService
    extends Service
{

    private final static URL PRODUCTSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTSOAPSERVICE_EXCEPTION;
    private final static QName PRODUCTSOAPSERVICE_QNAME = new QName("http://SoapServices/", "ProductSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/a20da21/ProductSoapService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTSOAPSERVICE_WSDL_LOCATION = url;
        PRODUCTSOAPSERVICE_EXCEPTION = e;
    }

    public ProductSoapService() {
        super(__getWsdlLocation(), PRODUCTSOAPSERVICE_QNAME);
    }

    public ProductSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTSOAPSERVICE_QNAME, features);
    }

    public ProductSoapService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTSOAPSERVICE_QNAME);
    }

    public ProductSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTSOAPSERVICE_QNAME, features);
    }

    public ProductSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductSoap
     */
    @WebEndpoint(name = "ProductSoap")
    public ProductSoap getProductSoap() {
        return super.getPort(new QName("http://SoapServices/", "ProductSoap"), ProductSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductSoap
     */
    @WebEndpoint(name = "ProductSoap")
    public ProductSoap getProductSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://SoapServices/", "ProductSoap"), ProductSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTSOAPSERVICE_EXCEPTION!= null) {
            throw PRODUCTSOAPSERVICE_EXCEPTION;
        }
        return PRODUCTSOAPSERVICE_WSDL_LOCATION;
    }

}
